services:
#  weather:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8181:8181'
#    env_file:
#      - .env.firebase-local
#    environment:
#      - FIREBASE_TYPE
#      - FIREBASE_PROJECT_ID
#      - FIREBASE_PRIVATE_KEY_ID
#      - FIREBASE_PRIVATE_KEY
#      - FIREBASE_CLIENT_EMAIL
#      - FIREBASE_CLIENT_ID
#      - FIREBASE_AUTH_URI
#      - FIREBASE_TOKEN_URI
#      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL
#      - FIREBASE_CLIENT_X509_CERT_URL
#      - FIREBASE_UNIVERSE_DOMAIN
#    volumes:
#      - weather-data:/app
#    depends_on:
#      - redis
#      - postgres

  redis:
    image: redis:7.4.0-alpine
    volumes:
      - redis-data:/app/redis/data
    ports:
      - '6379:6379'
    env_file:
      - .env.redis-local
    environment:
      - REDIS_ADDRESS
      - REDIS_PASSWORD
      - REDIS_DB
      - REDIS_TIMEOUT

  postgres:
    image: postgres:17.0-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env.postgres-local
    environment:
      - POSTGRES_DATABASE
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_SSL_MODE
      - POSTGRES_USER
      - POSTGRES_TIMEZONE

  sonarqube-db:
    image: postgres:17.0-alpine
    container_name: weather-wrapper-sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - sonarnet

  sonarqube:
    image: sonarqube:9.9-community
    container_name: weather-wrapper-sonarqube
    depends_on:
      - sonarqube-db
    ports:
      - '9000:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonarnet

volumes:
  weather-data:
  redis-data:
  postgres-data:
  sonarqube_db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  sonarnet:

#  sqp_a715c69f712d3bfcd636165f4f41f3cb563b4100